# Generated by Django 5.2.1 on 2025-08-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_created_at_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.ImageField(upload_to='comments_media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(upload_to='posts_media'),
        ),
    ]
