# Generated by Django 5.2.1 on 2025-08-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_onlineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineuser',
            name='channel_name',
            field=models.TextField(default=''),
        ),
    ]
