# Generated by Django 5.2.1 on 2025-07-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_remove_author_user_author_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='name',
        ),
    ]
