# Generated by Django 5.2.1 on 2025-07-17 22:54

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_chat_alter_message_author_message_chat_delete_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 0, 54, 41, 815448)),
        ),
    ]
