# Generated by Django 5.2.1 on 2025-07-17 23:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_chat_participants_alter_chat_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 1, 34, 46, 861817)),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.chat'),
        ),
    ]
