# Generated by Django 5.2.1 on 2025-07-25 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_alter_chat_last_message_alter_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 15, 50, 26, 988374)),
        ),
    ]
