# Generated by Django 5.2.1 on 2025-08-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_chat_created_at_alter_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_image',
            field=models.ImageField(default='chat_image_default.png', upload_to='chat_image'),
        ),
    ]
